### ISSUE TITLE
Valheim.exe

### ISSUE THREAD

**Issue by Horem** [karkkant/valheim-solid_hitboxes#1]
You are referencing the Valheim.exe in Plugins.cs which will prevent your mod loading/been used on a server, making your server sync kinda moot ;)

**Comment by karkkant** [comment]
Haha, good catch! Removed the target attribute for version 1.0.1. Thanks for reporting. :)

**Comment by vitalikbyrevich** [comment]
> Haha, good catch! Removed the target attribute for version 1.0.1. Thanks for reporting. :)

Can I ask you to keep a "list of changes"?) To understand whether it is worth downloading a new version or not) If it's not difficult of course)
