### ISSUE TITLE
[bug?] No FF DMG grom some mobs

### ISSUE THREAD

**Issue by Juraszka** [karkkant/valheim-solid_hitboxes#2]
Players from my dedicated server notice me that some mobs don't do dmg to thier friends. Trolla do DMG to other mobs but eg. greys don't hurt another grey.
On server config ff is turned ON.
If players don't have this option set to on, itn will be uto synced with serwer?

**Comment by karkkant** [comment]
Yes server config is synced with players when they join server.

There are two ways I can imagine this could happen:
1) Not all players had the mod running
2) For some reason the config was not synced

I'd double check that everyone has the mod. Also if you are admin, you can toggle AI FF to off and back on through console or chat, doing that will re-sync config with all connected players.
